name: flutter_sensors
description: A flutter plugin to access the available sensors of the device (forked from https://github.com/LJaraCastillo/flutter_sensors).
version: 2.0.0
homepage: https://github.com/ToufiPF/flutter_sensors
repository: https://github.com/ToufiPF/flutter_sensors

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: cl.ceisufro.fluttersensors
        pluginClass: FlutterSensorsPlugin
      ios:
        pluginClass: FlutterSensorsPlugin
